### PR TITLE
[DRAFT] Implement some useful L2 functions

### PR DESCRIPTION
**Pull request by jamesaevans**
For @jlumbroso's review, this DRAFT PR implements `codepost.assignments.retrieve_by_name`

### CODE REVIEW

**Comment by jlumbroso** [comment]
@jamesaevans What is rationale of placing additional L2 functions inside the abstract REST API models?

I was thinking more along the lines of creating a helpers.py module that contains all those functions. There are a bunch of reasons, but I guess I would like:

- Our REST API models to mirror the documented API (L1 functions).

- Any additional method to be in some separate module (L2 functions).

The reason why is that I expect the L1 functions will remain the same across language bindings, but that the L2 functions might be different across languages. I think it's cleaner to explain those differences if the methods are clearly labeled as helper methods.

I also anticipate that L2/L3 functions will soon involve methods created custom for our users, and it may become junky soon. I don't want that junkiness to saturate the namespace of the REST API models.

**Comment by jamesaevans** [comment]
I think to answer this question we need to align on a definition of L1 and L2. Here's an attempt:
* L1 = basic CRUD operations (which you've cleanly encapsulated in `api_crud.py`)
* L2 = any operation performed on an object but not a basic CRUD operation. This would include `assignment.retrieve_by_name` as well as `assignment.list_submissions` (even though the former involves a combination of API calls, and the latter a single call). This definition explicitly prioritizes ease-of-use over. I imagine most consumers of the SDK will view these two functions similarly: they are both sort-of-more-complicated operations I perform on an assignment. **I propose these functions live in the REST API models.**
* L3 = any operation involving multiple objects, combining a number of L1 and L2 functions. **I propose these functions live in a `helpers.py` module, as you suggest. 

> The reason why is that I expect the L1 functions will remain the same across language bindings, but that the L2 functions might be different across languages. I think it's cleaner to explain those differences if the methods are clearly labeled as helper methods.

This is a valid concern. My hunch is that L2 (as defined above) will likely remain consistent across language bindings, while L3 (again, as defined above) may not.

**Comment by jlumbroso** [comment]
> I think to answer this question we need to align on a definition of L1 and L2. Here's an attempt:

I think this is a great formalization of L1-L3 that we were discussing.

I feel gross about adding methods to the models, because I see them just as a factory for objects, but I guess I could compromise.

> This is a valid concern. My hunch is that L2 (as defined above) will likely remain consistent across language bindings, while L3 (again, as defined above) may not.

I have strong doubts here. My experience so far has been that if you don't nail a standard down, it does not remain consistent. (Cf. indentation, naming.) I'd feel better if we hashed out exactly what is L2 before implementing them—and kept that list as reference for other bindings.

(@jamesaevans The other thing to keep in mind is that in a future strategy, we might have the L1 REST API generated through OpenAPI, which means it will always be more convenient to separate those automatically generated bindings from macro functions on top.)

**Comment by jlumbroso** [comment]
@jamesaevans By the way, wow, I love `_retrieve_related_objects`!! Very elegant mechanism.

**Comment by jlumbroso** [comment]
@jamesaevans I think this functionality is now addressed by https://github.com/codepost-io/codepost-python/commit/59f7a60171b0e2904053391b1f224ca97f5c1986, and this PR and associated branch can be closed. Do you concur?

**Comment by jamesaevans** [comment]
Agreed. This PR is a small, small subset of https://github.com/codepost-io/codepost-python/commit/59f7a60171b0e2904053391b1f224ca97f5c1986

**Pull request closed without merging**
